export const types = Object.freeze({
    //Async
    GET_PRODUCTS_ASYNC:        'GET_PRODUCTS_ASYNC',
    GET_PRODUCTS_FILTER_ASYNC: 'GET_PRODUCTS_FILTER_ASYNC',

    //Sync
    GET_PRODUCTS:        'GET_PRODUCTS',
    GET_PRODUCTS_FILTER: 'GET_PRODUCTS_FILTER',

    //Server
    GET_PRODUCTS_SERVER: 'GET_PRODUCTS_SERVER',
});
