export const START_FETCH_PRODUCT = 'START_FETCH_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const IS_FETCHING_PRODUCT = 'IS_FETCHING_PRODUCT';
export const RESET_SERVER_FLAG = 'RESET_SERVER_FLAG';
export const SERVER_FLAG_TO_FALSE = 'SERVER_TO_FALSE';


export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const START_FETCH_PRODUCTS = 'START_FETCH_PRODUCTS';

//Spinner
export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';
